### ISSUE TITLE
IE11 not working

### ISSUE THREAD

**Issue by Christian50-ger** [sjaakp/telex#5]
i test the demo https://www.sjaakpriester.nl/software/telex
and works great in all Browser, but in IE 11 not!
is there a way for IE11 to work?
Thanks

**Comment by sjaakp** [comment]
No, Telex doesn’t work in IE11. I’m sorry!

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: Christian50-ger <notifications@github.com> 
Verzonden: vrijdag 22 mei 2020 18:01
Aan: sjaakp/telex <telex@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/telex] IE11 not working (#5)

 

i test the demo https://www.sjaakpriester.nl/software/telex
and works great in all Browser, but in IE 11 not!
is there a way for IE11 to work?
Thanks
